export const data = [
	{	isLatest: true,
		isBestSeller: true,
		name: 'Apple Iphone 11, 256GB, blue',
		price: 600,
		prevPrice: 800,
		description: "The iPhone 12 and iPhone 12 mini are Apple's mainstream flagship iPhones for 2020. The phones come in 6.1-inch and 5.4-inch sizes with identical features, including support for faster 5G cellular networks, OLED displays, improved cameras, and Apple's latest A14 chip, all in a completely refreshed design.",
		haveAmount: 25,	
	},
	{	isLatest: true,
		isBestSeller: true,
		name: 'Apple Iphone 12, 256GB, blue',
		price: 600,
		description: "The iPhone 12 and iPhone 12 mini are Apple's mainstream flagship iPhones for 2020. The phones come in 6.1-inch and 5.4-inch sizes with identical features, including support for faster 5G cellular networks, OLED displays, improved cameras, and Apple's latest A14 chip, all in a completely refreshed design.",
		haveAmount: 25,	
	},
	{	isLatest: true,
		isBestSeller: false,
		name: 'Apple Iphone 10, 256GB, blue',
		price: 600,
		description: "The iPhone 12 and iPhone 12 mini are Apple's mainstream flagship iPhones for 2020. The phones come in 6.1-inch and 5.4-inch sizes with identical features, including support for faster 5G cellular networks, OLED displays, improved cameras, and Apple's latest A14 chip, all in a completely refreshed design.",
		haveAmount: 25,	
	},
	{	isLatest: false,
		isBestSeller: true,
		name: 'Apple Iphone 9, 256GB, blue',
		price: 600,
		description: "The iPhone 12 and iPhone 12 mini are Apple's mainstream flagship iPhones for 2020. The phones come in 6.1-inch and 5.4-inch sizes with identical features, including support for faster 5G cellular networks, OLED displays, improved cameras, and Apple's latest A14 chip, all in a completely refreshed design.",
		haveAmount: 25,	
	},
	{	isLatest: false,
		isBestSeller: false,
		name: 'Apple Iphone 8, 256GB, blue',
		price: 600,
		description: "The iPhone 12 and iPhone 12 mini are Apple's mainstream flagship iPhones for 2020. The phones come in 6.1-inch and 5.4-inch sizes with identical features, including support for faster 5G cellular networks, OLED displays, improved cameras, and Apple's latest A14 chip, all in a completely refreshed design.",
		haveAmount: 25,	
	},
	{	isLatest: true,
		isBestSeller: true,
		name: 'Apple Iphone 7, 256GB, blue',
		price: 600,
		description: "The iPhone 12 and iPhone 12 mini are Apple's mainstream flagship iPhones for 2020. The phones come in 6.1-inch and 5.4-inch sizes with identical features, including support for faster 5G cellular networks, OLED displays, improved cameras, and Apple's latest A14 chip, all in a completely refreshed design.",
		haveAmount: 25,	
	},
	{	isLatest: true,
		isBestSeller: true,
		name: 'Apple Iphone 6, 256GB, blue',
		price: 600,
		description: "The iPhone 12 and iPhone 12 mini are Apple's mainstream flagship iPhones for 2020. The phones come in 6.1-inch and 5.4-inch sizes with identical features, including support for faster 5G cellular networks, OLED displays, improved cameras, and Apple's latest A14 chip, all in a completely refreshed design.",
		haveAmount: 25,	
	},
	{	isLatest: true,
		isBestSeller: true,
		name: 'Apple Iphone 5, 256GB, blue',
		price: 600,
		description: "The iPhone 12 and iPhone 12 mini are Apple's mainstream flagship iPhones for 2020. The phones come in 6.1-inch and 5.4-inch sizes with identical features, including support for faster 5G cellular networks, OLED displays, improved cameras, and Apple's latest A14 chip, all in a completely refreshed design.",
		haveAmount: 25,	
	},
	{	isLatest: true,
		isBestSeller: true,
		name: 'Apple Iphone 4, 256GB, blue',
		price: 600,

		description: "The iPhone 12 and iPhone 12 mini are Apple's mainstream flagship iPhones for 2020. The phones come in 6.1-inch and 5.4-inch sizes with identical features, including support for faster 5G cellular networks, OLED displays, improved cameras, and Apple's latest A14 chip, all in a completely refreshed design.",
		haveAmount: 25,	
	},
	{	isLatest: true,
		isBestSeller: true,
		name: 'Apple Iphone 3, 256GB, blue',
		price: 600,
		description: "The iPhone 12 and iPhone 12 mini are Apple's mainstream flagship iPhones for 2020. The phones come in 6.1-inch and 5.4-inch sizes with identical features, including support for faster 5G cellular networks, OLED displays, improved cameras, and Apple's latest A14 chip, all in a completely refreshed design.",
		haveAmount: 25,	
	}
]